# Generated by Django 5.2 on 2025-04-22 20:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawCsv",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("EbayData", models.TextField(blank=True, null=True)),
                ("WalmartData", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
