# Generated by Django 5.2 on 2025-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawcsv",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
