# Generated by Django 5.2 on 2025-04-24 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_rawcsv_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawcsv",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
