# Generated by Django 5.2 on 2025-04-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0003_alter_rawcsv_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Key",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Client_Id", models.CharField(max_length=500)),
                ("Client_Secret", models.CharField(max_length=500)),
                ("Approved", models.BooleanField(default=False)),
            ],
        ),
    ]
